Article milestone1 pull request
blakbox23/tnw-news pull request #1
Opened 2021-03-30 15:44 UTC by ahzia

We have worked on the first milestone for "tnw-news" project;
We build 4 sections (Header, Footer, Highlights, and Latest Funding ) for three screens (Mobile, Tablet and laptop)
Kindley Review our code.
Thanks

2021-03-30 19:33 UTC, henatan99 requested changes
# Changes Required #:recycle: 
Hey there, you have done a lot so far, yet there are some changes you need to make before the project gets approved.
### Please be aware that this is your first review and you will be left with only two re-reviews. If your project cannot be approved in the second re-review(third review), you will repeat the project. 
## To Highlight 
### General requirements 
- PR has a descriptive title and a nice summary 
- Cool commit messages 
- Correct Git flow 
### Project-specific 
- Nicely behaving responsive design for 1024px min and 768px min breakpoints
- Mobile-first design approach is followed
- Footer and header elements are properly aligned using flex 
- Grid is nicely employed in the highlights section 

## To Improve 
- In the Highlight section, the highlight center p-tag texts positioning is not as the original design in the 768px min and 1024px min views
- For good semantic's sake, you should make the 'highlight-one', 'highlight-two' and 'highlight-three' elements article elements instead of div
- You should change the p-tags to hx-tags (headings) in the highlight-one, -two, and -three elements, and also should have a-tags, please refer to the inline comments 
- The logo 'TNW' does not have a-tag, so it should have 
- Header should stick to the top when the user scrolls the page 
- Use a-tag for all menu items, search button, and hamburger button (Please refer inline comments) 
- In mobile view, the yellow section(top-cta class) should have big top and bottom padding when it is mobile view 
- The hamburger button should disappear when it is tablet view 
- The date should appear over the highlight-one element, at the top right corner
- Please see inline comments for the latest-funding section comments 
- You forget the vertical-line(pipe) character in the latest funding nav element for tablet and desktop views 
- The social media icons in the footer should have a-tag

### Please make the requested changes and submit for re-review 

### Once again, Please be aware that this is your first review and you will be left with only two re-reviews. If your project cannot be approved in the second re-review(third review), you will repeat the project. 

###Happy Coding :computer:

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +              <li>Terms & conditions</li>
- All menu options should have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +              <li>Contact</li>
- All menu options should have a-tag (You can wrap a-tags by li-tags)

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +              <li>GROWTH QUARTERS</li>
- All menu options should have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +            <div><i class="fa fa-search search"></i></div>
- Search button needs to have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +            <div><i class="fa fa-bars menu"></i></div>
- search and hamburger buttons needs to have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +      <div class="highlight-one">
Change this tag to article

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +          <p>
This tag should be hx-tag(h1 or h2 or..)  and should have a-tag also

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +          <p>
Change this p-tag to hx-tag and also should have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +      <div class="highlight-two">
this div should be replaced by article tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +      <div class="highlight-three">
This div should be replaced by article tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +          <p>
Changes this p-tag with hx-tag and also should have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +        </ul>
- This ul should be wrapped by a nav element 
- All menu options (li items here) should have a-tag

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +                <p><i class="fa fa-briefcase"></i> Expedition growth capital</p>
These p-tags should also have a-tags. Please extrapolate this comment to the other latest-funding section div elements

2021-03-30 19:33 UTC, henatan99 commented on index.html
> +              </p>
This p-tag should also have a-tag. Please extrapolate this comment to the other latest funding section div elements

2021-03-31 16:23 UTC, DeliceLydia requested changes
# Status: Change Requested

Amazing job guys on implementing almost all changes the previous TSE 
asked to make however you still have small changes to make and you are ready for another milestone

- Hamburger button should disappear on the tablet
- The first article appears bigger on the left, and its title is bigger on tablet
- The other 2 articles appear smaller on the right, the second on top of the third on the tablet

### Implement those small changes and submit another CRR and remember after this review you still have one CR only so work accordingly


# Happy coding ![image](https://user-images.githubusercontent.com/44745855/113177604-01c93500-924e-11eb-93c9-226ab108291e.png)

Best,

Lydia Ingabire

2021-03-31 16:54 UTC, blakbox23 commented
@DeliceLydia  The hamburger dissapears on tablet view. This is a picture of the view on my end. Is there something I'm missing? This is the tablet view

<img width="744" alt="Menu" src="https://user-images.githubusercontent.com/36844547/113181828-df89e400-925a-11eb-8de0-87f73335e7b4.PNG">

2021-03-31 17:20 UTC, DeliceLydia commented
@blakbox23 thanks for reaching out it might be my computer with a bigger 
screen don't mind about that then move on

![tnw](https://user-images.githubusercontent.com/44745855/113184935-16113000-9256-11eb-891f-613a7438930a.png)

2021-03-31 18:18 UTC, blakbox23 commented
I have the changed the sizes of the highlights as well as the font sizes for the two articles 
@DeliceLydia

2021-03-31 18:36 UTC, DeliceLydia commented
Okey submit for another CR and hopefully you are good to go

2021-03-31 19:44 UTC, henatan99 approved these changes
# Project Approved :100:

## Congratulations your project is approved :+1: :partying_face: . Thank you for implementing the requested changes from the last review. 

For optional improvements you can refer the below comments 
## To Highlight 
- Nice responsive design 
- Using a-tags wherever required and nice use of semantic tags

## [OPTIONAL] Improvements 
- The highlights section grid is faulty in tablet and desktop views. Please check the inline comment 
- Change both nav menus to nav tag from div tag. See inline comments 

### You can now merge the PR and submit the mandatory project completion form 
### Happy Coding :computer: :computer_mouse:

2021-03-31 19:44 UTC, henatan99 commented on style.css
> +  }
Please correct this grid parameter as it is giving a faulty grid as shown in the screenshot. 
![Screenshot from 2021-04-01 00-17-39](https://user-images.githubusercontent.com/64894927/113199163-7b254f80-926f-11eb-9641-1664131ce31e.png)

2021-03-31 19:44 UTC, henatan99 commented on index.html
> +          <div class="blackback flex">
This tag should be a nav

2021-03-31 19:44 UTC, henatan99 commented on index.html
> +          <div class="search-menu-bg flex">
this tag should  be a nav

2021-03-31 21:01 UTC, merged