Article milestone2
blakbox23/tnw-news pull request #2
Opened 2021-04-01 15:51 UTC by blakbox23

This is milestone 2 of the project.

2021-04-01 20:01 UTC, henatan99 requested changes
# Changes Required :recycle:
Hi there, you did amazing work on this project. :clap: :clap: But you need to work on some mandatory improvements before your project gets approved. Please check the comments below.

### Reminder: This is your first review and you will have a maximum of only two more reviews (re-reviews) left. Please make sure you make all the requested changes before re-submission. 
## To Highlight
- Nice project organization 
- You have made a very nice clone of the original page 
- Very nice responsive design 

## To Improve [MANDATORY]
- Apply semantic tags for article elements 
- Please use proper hx-tags and a-tags in article elements of both the latest news, categories, and latest sections. See the inline comments 
- You forgot the yellow triangle price tag element in the latest deals articles on tablet and desktop views

### Please make the requested changes and submit for re-review. Be reminded that you have a maximum of two more reviews and if your project is not approved in the third review you will repeat the project. 

### Happy coding :computer: :computer_mouse:

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +            <p class="latest-news-bg-text">
- Change the p-tag to proper hx - tag and also add a-tag for this element. Extrapolate this comment to other latest-news articles also

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +              <p class="categories-mostpop-footer">Ivan Mehta 1 day ago</p>
- Change this p-tag into appropriate hx - tag and also warp it with or embed in a-tag to this element. Please extrapolate this comment to the other categories too.

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +              <p class="categories-latest-txt2">
- Change this p-tag to proper hx-tag and also add a-tag for linking. Please extrapolate this comment to the other similar articles in categories section too.

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +              </li>
- Al the list elements here should have embedded a-tag. This comment works for the other list elements in other ul wrappers in categories section

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +        <p>See all details</p>
-This element should also have a - tag

2021-04-01 20:01 UTC, henatan99 commented on index.html
> +            </p>
-This p-tag should be a proper hx-tag and add link to it (a-tag). This comment applies to the other articles in the latest-deal section.

2021-04-02 12:11 UTC, DeliceLydia approved these changes
# Status: Approved ![image](https://user-images.githubusercontent.com/44745855/113414126-88038980-93bc-11eb-94c1-c0848201a4d8.png)

Congratulations @blakbox23  and @ahzia for such hard work your project looks amazing it speaks by itself how much you worked hard and you implemented all changes requested by the previous TSE

### Optional
Reduce padding between the highlights section and the latest news on the big screen it doesn't look good

## Kudos once again feel free to merge and move on to the next project

All the best,

Lydia Ingabire

2021-04-02 12:28 UTC, merged